/**
 * Knowledge Matcher — tag-based knowledge retrieval (zero LLM calls).
 *
 * Knowledge is extracted and tagged by the LLM during flushPending's
 * structured summarization. This module only does code-level matching
 * of user keywords against those pre-computed tags.
 *
 * Flow:
 *   1. extractKeywords() from user prompt (code, zero cost)
 *   2. tagMatchGraph() scores entries by tag/keyword overlap (code, zero cost)
 *   3. serializeForInjection() formats top entries for context
 *
 * Total: 0 LLM calls, <1ms latency.
 */

import type { FileKnowledge, KnowledgeGraphMap } from "./types.js";

// ── Keyword extraction (code, zero cost) ────────────────────────────────────

/** Extract candidate keywords from user prompt. */
export function extractKeywords(prompt: string): string[] {
  const keywords: string[] = [];

  // 1. Quoted strings: "src/foo.ts" or 'validateEmail' or `template`
  const quoted = prompt.match(/['"`]([^'"`]+)['"`]/g) ?? [];
  for (const q of quoted) {
    keywords.push(q.slice(1, -1));
  }

  // 2. File paths: src/foo.ts, ./bar/baz.ts, ~/config.rs
  const paths = prompt.match(/(?:src\/|\.\.?\/|~\/)[\w.-]+(?:\/[\w.-]+)*/g) ?? [];
  keywords.push(...paths);

  // 3. CamelCase/PascalCase identifiers (2+ segments): validateEmail, FooBar
  const camel = prompt.match(/\b[A-Z][a-z]+(?:[A-Z][a-z]+)+\b|\b[a-z]+(?:[A-Z][a-z]+)+\b/g) ?? [];
  keywords.push(...camel);

  // 4. snake_case identifiers: parse_config, MIN_BATCH
  const snake = prompt.match(/\b[a-z]+(?:_[a-z]+)+\b|\b[A-Z]+(?:_[A-Z]+)+\b/gi) ?? [];
  keywords.push(...snake);

  // 5. kebab-case identifiers: my-component, foo-bar
  const kebab = prompt.match(/\b[a-z]+(?:-[a-z]+){1,}\b/g) ?? [];
  keywords.push(...kebab);

  // 6. $variable — dollar-sign prefixed variables
  const dollar = prompt.match(/\$([a-zA-Z_]\w{1,})/g) ?? [];
  keywords.push(...dollar);

  // 7. <Component /> JSX / HTML tag names (capture just the name)
  const jsx = prompt.match(/<([A-Z][a-zA-Z0-9]+)(?:\s|\/|>)/g) ?? [];
  for (const tag of jsx) {
    keywords.push(tag.slice(1).replace(/[\s\/>,].*$/, ""));
  }

  // 8. #[...] macro / attribute patterns (Rust, etc.)
  const macro = prompt.match(/#\[([\w()]+)\]/g) ?? [];
  for (const m of macro) {
    keywords.push(m);
  }

  // Deduplicate
  return [...new Set(keywords.filter((k) => k.length >= 2))];
}

// ── Tag-based matching (code, zero cost) ────────────────────────────────────

/**
 * Match knowledge graph entries against user keywords using pre-computed tags.
 * The tags were generated by the LLM during flushPending summarization,
 * so this is purely code-level matching — no LLM calls.
 */
export function tagMatchGraph(
  graph: KnowledgeGraphMap,
  keywords: string[]
): Array<{ entry: FileKnowledge; score: number; matchedTags: string[] }> {
  const candidates: Array<{ entry: FileKnowledge; score: number; matchedTags: string[] }> = [];

  for (const entry of graph.values()) {
    let score = 0;
    const matchedTags: string[] = [];

    // Pre-compute path segments for segment-level matching
    const pathSegments = entry.path.toLowerCase().split(/[\/\\.]/);
    // Merge all searchable text: tags + exports + path segments
    const allTags = new Set([
      ...entry.tags.map((t) => t.toLowerCase()),
      ...entry.exports.map((e) => e.toLowerCase()),
      ...pathSegments,
    ]);

    for (const kw of keywords) {
      const kwLower = kw.toLowerCase();

      // 1. Tag match (highest weight — LLM said this tag describes the file)
      for (const tag of allTags) {
        if (tag === kwLower || tag.includes(kwLower) || kwLower.includes(tag)) {
          score += 10;
          matchedTags.push(tag);
          break;
        }
      }

      // 2. Path match (high weight, but only for path-like keywords)
      if (kw.includes("/") || kw.includes(".")) {
        if (entry.path.toLowerCase().includes(kwLower)) {
          score += 8;
          matchedTags.push(`path:${kw}`);
        }
      }

      // 3. Structure match (medium weight)
      for (const struct of entry.structure) {
        if (struct.toLowerCase().includes(kwLower)) {
          score += 5;
          matchedTags.push(`struct:${kw}`);
          break;
        }
      }

      // 4. Changes match (medium weight)
      for (const change of entry.changes) {
        if (change.toLowerCase().includes(kwLower)) {
          score += 4;
          matchedTags.push(`change:${kw}`);
          break;
        }
      }
    }

    // Recency boost: recently touched files slightly preferred
    const maxTurn = Math.max(entry.lastEditTurn, entry.lastReadTurn);
    if (maxTurn > 0) score += 1;

    if (score > 0) {
      candidates.push({ entry, score, matchedTags });
    }
  }

  // Sort by score descending
  candidates.sort((a, b) => b.score - a.score);
  return candidates;
}

// ── Serialization for injection ─────────────────────────────────────────────

/** Serialize top knowledge entries for context injection. */
export function serializeForInjection(
  entries: Array<FileKnowledge>,
  pathsWithActiveSummary?: Set<string>,
  maxEntries = 5
): string {
  if (entries.length === 0) return "";

  const sections: string[] = ["<relevant-knowledge>"];
  let count = 0;

  for (const entry of entries) {
    if (count >= maxEntries) break;

    // Skip files that already have an unpruned summary in context
    if (pathsWithActiveSummary?.has(entry.path)) continue;

    const parts: string[] = [];
    if (entry.exports.length > 0) {
      parts.push(`  exports: ${entry.exports.join(", ")}`);
    }
    if (entry.imports.length > 0) {
      parts.push(`  imports: ${entry.imports.slice(-3).join("; ")}`);
    }
    if (entry.structure.length > 0) {
      parts.push(`  structure:\n    ${entry.structure.slice(-5).join("\n    ")}`);
    }
    if (entry.changes.length > 0) {
      parts.push(`  changes: ${entry.changes.slice(-3).join("; ")}`);
    }

    if (parts.length > 0) {
      sections.push(`  ${entry.path}:`);
      sections.push(...parts);
      count++;
    }
  }

  sections.push("</relevant-knowledge>");

  if (count === 0) return "";
  return sections.join("\n");
}
